[package]
name = "icli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3", features=["string"]}
promkit = "0.1"
shlex = "1.1"
